services:
  backend:
    build:
      context: ./furniture_catalog
      dockerfile: Dockerfile
    # no host port; accessed via nginx and internal network
    env_file:
      - ./furniture_catalog/.env
    environment:
      - DEBUG=True
    volumes:
      - media_volume:/app/media
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./abt-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "/api"
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:8000/api
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=furniture_catalog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  postgres_data:
  media_volume:

networks:
  app-network:
    driver: bridge
