# Generated by Django 5.2.1 on 2025-05-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.style'),
        ),
    ]
