# Generated by Django 5.2.1 on 2025-05-31 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_material_product_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='styles',
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.style'),
        ),
    ]
