# Generated by Django 5.2 on 2025-06-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_product_styles_product_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstpage',
            name='photo',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
