# Generated by Django 5.2 on 2025-06-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_firstpage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstpage',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
