# Generated by Django 5.2.1 on 2025-07-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
