# Generated by Django 5.2.1 on 2025-12-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_firstpage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstpage',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
