# Generated by Django 5.2.1 on 2025-12-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_firstpage_title_alter_firstpage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstpage',
            name='title',
        ),
    ]
