# Generated by Django 5.2.1 on 2026-01-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstpage',
            name='mobile_photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
