# Generated by Django 5.2.1 on 2026-01-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
