# Generated by Django 5.2.1 on 2026-01-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_firstpage_mobile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
