# Generated by Codex on 2026-07-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_contactrequest_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstPage',
        ),
    ]
